---
- name: Make sure the installation directory exists
  ansible.builtin.file:
    path: "{{ poetry_home }}"
    state: directory
    mode: 0755

- name: Download the installation script
  ansible.builtin.get_url:
    url: https://install.python-poetry.org
    dest: "{{ poetry_installation_script }}"
    mode: 0755

- name: Install Poetry at {{ poetry_home }} (max 30 minutes, poll every 10 seconds)
  environment:
    POETRY_VERSION: "{{ poetry_version }}"
    POETRY_HOME: "{{ poetry_home }}"
  vars:
    already_installed_expr: "{{ ('version (' ~ poetry_version ~ ') is already installed.') | regex_escape() }}"
  ansible.builtin.command:
    argv:
      - python3
      - "{{ poetry_installation_script }}"
  async: 1800
  poll: 10
  changed_when: not (poetry_installation_result['stdout'] | regex_search(already_installed_expr))
  register: poetry_installation_result

- name: Verify the installation
  become: false
  ansible.builtin.command:
    argv:
      - "{{ poetry_home }}/bin/poetry"
      - --version
  changed_when: false
  register: poetry_verification_result

- name: Add Poetry's bin directory to PATH
  ansible.builtin.template:
    src: "{{ poetry_env_filename }}.j2"
    dest: "/etc/profile.d/{{ poetry_env_filename }}"
    owner: root
    group: root
    mode: 0755
    force: true
  when: poetry_verification_result is success

- name: Create a directory if it does not exist
  become: true
  ansible.builtin.file:
    path: /etc/bash_completion.d
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Run Bash completions command
  ansible.builtin.command: "{{ poetry_home | quote }}/bin/poetry completions bash"
  register: "output"
  changed_when: false
  when: poetry_verification_result is success

- name: Save the Bash completions output to a file
  ansible.builtin.copy: 
    content: "{{ output }}"
    dest: "/etc/bash_completion.d/poetry.bash-completion"
    
