---

- name: check if conda is present
  ansible.builtin.command: conda --version
  changed_when: false
  failed_when: false
  register: cmd_conda_version

- name: download miniconda
  ansible.builtin.get_url:
    url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    dest: /tmp/install-miniconda.sh
    mode: 0755
  when: cmd_conda_version.rc != 0

- name: create conda folder
  become: true
  ansible.builtin.file:
    path: /opt/miniconda
    state: directory
    owner: root
    group: root
    mode: 0755

- name: run miniconda installer
  ansible.builtin.command: /tmp/install-miniconda.sh -b -u -p /opt/miniconda
  when: cmd_conda_version.rc != 0

- name: remove miniconda installer
  ansible.builtin.file:
    state: absent
    path: /tmp/install-miniconda.sh

- name: add to path
  become: true
  ansible.builtin.copy:
    dest: "/etc/profile.d/miniconda.sh"
    content: |
      export PATH=/opt/miniconda/bin:$PATH
    owner: root
    group: root
    mode: 0755

# - name: add PATH and initialize
#   shell: export PATH=/opt/miniconda/bin:$PATH && conda init
#   args:
#     executable: /bin/bash

- name: miniconda +r+x for all
  become: true
  ansible.builtin.file:
    path: /opt/miniconda
    mode: 0755
    recurse: true
