name: Lint Code Base

on:
  push:
    branches:
      - main
      - TestBranch_AnsibleLint 
  pull_request:
    branches:
      - "*"

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Run ansible requirements
        run: ansible-galaxy collection install community.general
        
      - name: dhfsgfk
        run: |
          pwd
          cd /home/runner/
          ls -la
          cd /home/runner/work
          ls
          cd /home/runner/.ansible/collections
          ls

          
      - name: Lint ansible project
        uses: ansible-community/ansible-lint-action@v6
